# raw.py: corpus v2's raw code (docs/CORPUS-V2.md, C4, C6): every raw file run 1 was
# fed or queued (code-train-v3: raw1-9; run/raw-new's deliveries: mix 1 (nr) and
# mix 2 (ns)), by language, each file once, less what v2 holds out and what the
# transcript windows already use as filler; then the shared filters; shuffled by a
# hash of the id, so any prefix samples the whole pool evenly.
#   run/v2/raw/LANG.jsonl ({"id","text"}, bend-mix's input), run/v2/raw/summary.txt
# Filters: a line over 2,000 characters (data, minified, generated); a generated-file
# marker in the first 1,000 bytes; Lean 3 (`import data.`/`begin` ... `end` proofs);
# repository caps (Haskell 8 MB, Lean 15 MB, Agda 10 MB), first files by hash order kept.
import sys, os, json, hashlib, collections, random
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from names import repo_of, path_of
from norm_hash import key

SOURCES = ["run/code-train-v3.jsonl",
           "run/raw-new/haskell.jsonl", "run/raw-new/haskell-2.jsonl", "run/raw-new/agda-f.jsonl", "run/raw-new/agda-2f.jsonl",
           "run/raw-new/lean.jsonl", "run/raw-new/lean-2.jsonl", "run/raw-new/bend.jsonl"]
EXT = {"hs": "haskell", "lhs": "haskell", "lean": "lean", "agda": "agda", "lagda": "agda", "nix": "nix", "bend": "bend"}
CAP = {"haskell": 8_000_000, "lean": 15_000_000, "agda": 10_000_000}
GEN = ["DO NOT EDIT", "do not edit", "Code generated", "auto-generated", "autogenerated", "Automatically generated",
       "This file was generated", "This file is generated", "generated by"]
O = "run/v2/raw"

def lang_of(i):
    n = path_of(i).lower()
    if n.endswith(".lagda.md") or n.endswith(".lagda.tex"): return "agda"
    return EXT.get(n.rsplit(".", 1)[-1] if "." in n else "")

xp = set(open("run/v2/holdout/exclude.paths").read().splitlines())
xk = set(open("run/v2/holdout/exclude.sha256").read().splitlines())
xu = {l.split("\t")[0] for l in open("run/v2/holdout/units.tsv").read().splitlines()[1:]}
fk = set(open("run/v2/transcripts/filler.keys").read().splitlines())

def held(i, k):
    r, p = repo_of(i), path_of(i)
    return (r in xu or f"{r}/{p.rsplit('/', 1)[0] if '/' in p else ''}" in xu or f"{r}/{p}" in xu
            or f"{r}\t{p}" in xp or k in xk)

def why_not(lang, t):
    if any(len(l) > 2000 for l in t.split("\n")): return "long line"
    if any(g in t[:1000] for g in GEN): return "generated"
    if lang == "lean" and ("\nimport data." in "\n" + t[:2000] or ("\nbegin\n" in t and "\nend" in t)): return "lean 3"
    return None

os.makedirs(O, exist_ok=True)
seen = set(); keep = collections.defaultdict(list); st = collections.defaultdict(collections.Counter)
for src in SOURCES:
    with open(src, encoding="utf-8", errors="replace") as f:
        for line in f:
            try: d = json.loads(line)
            except ValueError: continue
            i, t = d["id"], d["text"]; lang = lang_of(i)
            if lang is None: continue
            c = st[lang]; k = key(t)
            if k in seen: c["copy"] += 1; continue
            seen.add(k)
            if held(i, k): c["held out"] += 1; continue
            if k in fk: c["filler"] += 1; continue
            w = why_not(lang, t)
            if w: c[w] += 1; continue
            keep[lang].append((hashlib.sha256(("corpus-v2 raw\0" + i).encode()).hexdigest(), i, t))
out = []
for lang, xs in sorted(keep.items()):
    xs.sort(); per = collections.Counter(); c = st[lang]; n = b = 0
    with open(f"{O}/{lang}.jsonl", "w", encoding="utf-8") as o:
        for _, i, t in xs:
            r = repo_of(i)
            if lang in CAP and per[r] + len(t) > CAP[lang]: c["repo cap"] += 1; continue
            per[r] += len(t)
            o.write(json.dumps({"id": i, "text": t}, ensure_ascii=False) + "\n"); n += 1; b += len(t)
    out.append(f"{lang:8} kept {n:7d} files {b / 1e6:8.1f} MB; " + ", ".join(f"{k} {v}" for k, v in sorted(c.items())))
open(f"{O}/summary.txt", "w").write("\n".join(out) + "\n")
print("\n".join(out))
